language: android

jdk:
  - oraclejdk8

android:
  components:
    - build-tools-25.0.0
    - android-25
  licenses:
    - 'android-sdk-license-5be876d5'
script:
    - ./gradlew test

after_success:
    - ./gradlew jacoco coveralls
