language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.0
    - android-25
  licenses:
    - 8933bad161af4178b1185d1a37fbf41ea5269c55
script:
    - ./gradlew test

after_success:
    - ./gradlew jacoco coveralls
