language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.0
  licenses:
    - 'android-sdk-license-.+'
script:
    - ./gradlew test

after_success:
    - ./gradlew jacoco coveralls
