language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.3
    - extra-google-m2repository
    - extra-android-m2repository

install:
  - android-update-sdk --accept-licenses='android-sdk-license-.+' --components=tools
  - android-update-sdk --accept-licenses='android-sdk-license-.+' --components=build-tools-25.0.3
  - android-update-sdk --accept-licenses='android-sdk-license-.+' --components=extra-android-m2repository
  - android-update-sdk --accept-licenses='android-sdk-license-.+' --components=extra-google-m2repository

script:
  - ./gradlew test

after_success:
  - ./gradlew jacocoTestReport coveralls
