language: android

jdk:
  - oraclejdk8

android:
  components:
#    - platform-tools
#    - tools
    # ビルドツールバージョン
    - build-tools-24.0.2
    - extra-android-support
    # Android SDKバージョン
    - android-24
  licenses:
    - 'android-sdk-license-.+'

script:
    - ./gradlew test

after_success:
    - ./gradlew jacoco coveralls
